#!/usr/bin/bash

# unlink /etc/eos.keytab 2>/dev/null;
# yes | xrdsssadmin -k eos -u daemon -g daemon add /etc/eos.keytab >& /dev/null;

chmod 600 /etc/eos.keytab 2>/dev/null;
chown daemon:daemon /etc/eos.keytab >& /dev/null;
chmod 400 /etc/eos.keytab;

# prepare directories
mkdir -p               /var/log/quarkdb/ /var/spool/quarkdb/
chown -R daemon:daemon /var/log/quarkdb/ /var/spool/quarkdb/

# create quarkdb configuration files
# this scenario if for all 3 instances on the same node
# for different nodes just create and scp the files to remote endpoints

# See file xrd.cf.quarkdb0

# Prepare the log and working directories for the instances
chown -R daemon:daemon "${CFGFILE}"

# create customize the systemd init file N.B. is a customization not a replacement!!
# see xrootd@quarkdb0.service.d/custom.conf

# quarkdb-create --path /var/lib/quarkdb/qdb0/ --clusterID "${CLUSTERID}"
#  --nodes mgm1.spacescience.ro:7000,mgm2.spacescience.ro:7000,mgm3.spacescience.ro:7000

# Change ownership to daemon:daemon
chown -R daemon:daemon /var/lib/quarkdb

# start and check the services

