#!/usr/bin/bash

# This file contains private quarkdb information
# REDIS_PASS and CLUSTERID are defined there
source ./quarkdb_priv

chmod 600 /etc/eos.keytab 2>/dev/null;
unlink /etc/eos.keytab 2>/dev/null;
yes | xrdsssadmin -k eos -u daemon -g daemon add /etc/eos.keytab >& /dev/null;
chown daemon:daemon /etc/eos.keytab >& /dev/null;
chmod 400 /etc/eos.keytab;

# prepare directories
mkdir -p               /var/log/quarkdb/ /var/spool/quarkdb/
chown -R daemon:daemon /var/log/quarkdb/ /var/spool/quarkdb/

# create quarkdb configuration files
# this scenario if for all 3 instances on the same node
# for different nodes just create and scp the files to remote endpoints
for i in {1..3}; do
    CFGFILE="/etc/xrootd/xrootd-quarkdb${i}.cfg"
    # Create one configuration file per instance
    cp /etc/xrootd/xrootd-quarkdb.cfg "${CFGFILE}"

    # Customize the port
    sed -i "s/7777/700${i}/g" "${CFGFILE}"

    # Customize the storage location
    sed -i "/redis\.database/s/.*/  redis\.database \/var\/lib\/quarkdb\/qdb${i}/g" "${CFGFILE}"

    # set password
    sed -i "/redis\.password/s/.*/  redis\.password ${REDIS_PASS}/g" "${CFGFILE}"

    # Add myself entry to the config
    sed -i "s/^fi/  redis.myself localhost:700${i}\n&/" "${CFGFILE}"

    # Prepare the log and working directories for the instances
    chown -R daemon:daemon "${CFGFILE}"

    # create customize the systemd init file N.B. is a customization not a replacement!!
    SYSTEMD_CUSTOM="/etc/systemd/system/xrootd@quarkdb${i}.service.d"
    mkdir -p ${SYSTEMD_CUSTOM}
  cat << EOF > ${SYSTEMD_CUSTOM}/custom.conf
[Service]
# automatically create /run/quarkdb${i}
RuntimeDirectory=quarkdb${i}
RuntimeDirectoryMode=0700
WorkingDirectory=/var/spool/quarkdb/

# uid:gid of the process
User=daemon
Group=daemon

# let's erase the initial definition of ExecStart
ExecStart=
# use explicit name for the logfile (no fenced)
ExecStart=/usr/bin/xrootd -l =/var/log/quarkdb/xrootd_${i}.log -c /etc/xrootd/xrootd-%i.cfg -k fifo -s /run/quarkdb${i}/xrootd-%i.pid -n %i
RestartSec=10

EOF

  quarkdb-create --path /var/lib/quarkdb/qdb${i}/ --clusterID "${CLUSTERID}" --nodes localhost:7001,localhost:7002,localhost:7003
  # Change ownership to daemon:daemon
  chown -R daemon:daemon /var/lib/quarkdb

done

# start and check the services
#for i in {1..3}; do
#    SRV="xrootd@quarkdb${i}.service"
#    systemctl restart ${SRV}
#    systemctl status -l ${SRV}
#    systemctl --quiet is-active ${SRV} && systemctl enable ${SRV}
#done


