#!/usr/bin/bash

help() {
echo "1st arg should be the ssh alias or host of fst
2nd arg is storage directories prefix
3rd arg is present is the name of space"
}

FSID="${}"
FST="${}"
MNT_DIR=${}

SPACE="default"

eos fs add -m ${FSID} $(uuidgen -r) ${FST}:1095 ${MNT_DIR} "${SPACE}.${FSID}" rw

#[[ -z "${1}" ]] && { help; exit; }
#[[ -z "${2}" ]] && { help; exit; }

#FST="${1}"
#MNT="${2}"


# eos node config fst02.spacescience.ro:1095 gw.rate=2000
# eos node config fst02.spacescience.ro:1095 gw.ntx=100
# eos node txgw fst02.spacescience.ro:1095 on
# eos node set fst02.spacescience.ro:1095 on

