#!/usr/bin/env bash

TGT="${1}"
shift

FST_LIST="fst01 fst02 fst03 fst04 fst05 fst06 fst07 fst08 fst09 fst10 fst12 fst13 fst14 fst15" # fst11

CTRL_OPT="-o ControlMaster=auto -o ControlPersist=120 -o ControlPath=~/.ssh/%r@%h:%p"
SCP_CMD="scp -4 -B -C -p ${CTRL_OPT}"

cp /etc/sysconfig/eos_env /tmp/eos_env
sed --follow-symlinks -i "/^XRD_ROLES=/s/.*/XRD_ROLES=\"fst\"/" /tmp/eos_env

sync_conf2fst () {
local FST
FST="${1}"

${SCP_CMD} /tmp/eos_env ${FST}:/etc/sysconfig/
${SCP_CMD} /etc/xrd.cf.fst ${FST}:/etc/
${SCP_CMD} /etc/eos.keytab ${FST}:/etc/
${SCP_CMD} /etc/quarkdb.pass ${FST}:/etc/
${SCP_CMD} /etc/ganglia/gmond.conf ${FST}:/etc/ganglia/
${SCP_CMD} /etc/mlsensor/mlsensor.properties ${FST}:/etc/mlsensor/
${SCP_CMD} iptables/iptables ${FST}:/etc/sysconfig/
${SCP_CMD} iptables/ip6tables ${FST}:/etc/sysconfig/

ssh ${CTRL_OPT} ${FST} "systemctl enable mlsensor iptables ip6tables eos.target eos@fst; systemctl restart mlsensor iptables ip6tables; chown daemon:daemon /storage* /etc/quarkdb.pass; systemctl restart eos@fst;"
}

if [[ -z ${TGT} ]]; then
    for fst in ${FST_LIST} ; do
        sync_conf2fst ${fst}
    done
else
    sync_conf2fst ${TGT}
fi
rm -rf /tmp/eos_env

